global using SearchComparisonNet.GUI.Converters;
global using SearchComparisonNet.GUI.ViewModels;
global using SearchComparisonNet.Kernel.Interfaces;
global using SearchComparisonNet.Kernel.Models;
global using SearchComparisonNet.ViewModelTests.Fakes;
global using System.Globalization;
global using System.Windows;
global using System.Windows.Threading;
global using Xunit;
